### ISSUE TITLE
OGLE?.txt and SIGWs.txt files do not exist in bounds folder.

### ISSUE THREAD

**Issue by Kourosh76** [bradkav/PBHbounds#12]
These two files do not exist in bounds folder, and therefore, PlotPBHbounds doesn't run correctly. Please check this issue.

**Comment by bradkav** [comment]
Hi! Thanks for pointing out the issue with "OGLE?.txt". I renamed the file to "OGLE-hint.txt" at some point but didn't update all the list-files and some of the scripts. In the [latest commit](https://github.com/bradkav/PBHbounds/commit/9f4c5e82d42a51f2d2fe7aa75beaebf18d451186), this should now be resolved, but please double-check.

As for SIGWs.txt, I'm actually adding that to the plots using the function `addSIGWprojections` which appears in most of the scripts, rather than by reading the data from bounds-files like with the other bounds. This is partly because the SIGW projections are just simple shaded regions. So there is no SIGWs.txt because it's not needed. Can you confirm what the problem is? Are the SIGW regions not showing (or are you getting some kind of error)?

**Comment by Kourosh76** [comment]
Thanks for your quick and thorough answer Dr. Kavanagh. Everything is fine now.

**Comment by bradkav** [comment]
Great. Let me know if there are any other issues :)
